-----------------------------------------
MultiCapa-Santiago 
-----------------------------------------

enable
configure terminal

ip dhcp snooping
ip dhcp snooping vlan 25,30,35
no ip dhcp snooping information option

ip arp inspection vlan 25,30,35

interface port-channel 1
 ip dhcp snooping trust
 ip arp inspection trust
 spanning-tree guard root
exit

end
write memory

