-----------------------------------------
Switch-RRHH (acceso, Santo Domingo - VLAN 10)
-----------------------------------------

enable
configure terminal

ip dhcp snooping
ip dhcp snooping vlan 10
no ip dhcp snooping information option

ip arp inspection vlan 10

interface range e0/0-1
 ip dhcp snooping trust
 ip arp inspection trust
exit

interface e0/2
 ip dhcp snooping limit rate 10
 ip arp inspection limit rate 15
 errdisable recovery cause arp-inspection
 errdisable recovery cause dhcp-rate-limit
 errdisable recovery interval 60
exit

end
write memory
