-----------------------------------------
Multicapa 1 y Multicapa 2 - Santo Domingo
-----------------------------------------

enable
configure terminal

ip domain-name tufuturo.com.do
crypto key generate rsa
2046
ip ssh version 2

username Efren privilege 15 password tigre
username Ezequiel privilege 15 password leon
username Oliver privilege 7 password aguila
username Justin privilege 7 password lobo
service password-encryption

access-list 10 permit 192.168.0.0 0.0.0.255
access-list 10 deny any log

line vty 0 4
exec-timeout 15
transport input ssh
login local
logging synchronous
access-class 10 in
exit

end
write memory
